version: '2.1'
services:
  ipfs:
    image: ipfs/kubo:latest
    restart: always
    environment:
      - IPFS_PATH=/data/ipfs
    network_mode: "host"
    command: ["daemon", "--migrate=true", "--agent-version-suffix=docker", "--enable-gc"]
    volumes:
      - ipfs:/data/ipfs
      - ./ipfs-init.sh:/container-init.d/ipfs-init.sh
    container_name: ipfs
    healthcheck:
        test: ["CMD", "wget", "http://localhost:8080/ipfs/QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn"]
        interval: 5s
        timeout: 1s
        retries: 5
  poa:
    depends_on:
      ipfs:
        condition: service_healthy
    image: disregardfiat/poa:0.0.2
    restart: unless-stopped
    command: ["./main", "-node", "2", "-username", "${ACCOUNT}", "-WS_PORT=8000", "-useWS=true", "-honeycomb=true", "-IPFS_PORT=5001"]
    network_mode: "host"
    container_name: poa
  api:
    depends_on:
      ipfs:
        condition: service_healthy
    build: .
    restart: unless-stopped
    environment:
      - PORT=5050
      - ENDPOINT=http://127.0.0.1
      - ENDPORT=5001
      - DOCKER=true
    network_mode: "host"
    volumes:
      - ./.env:/.env
    logging:
      options:
        max-size: "2m"
        max-file: "3"
    stdin_open: true
    tty: true
volumes:
  ipfs:
    driver: local